'use client'

import type { Language } from './i18n'

const whisperLangMap: Record<
  Language,
  string | undefined
> = {
  en: 'en',
  hi: 'hi',
  hinglish: undefined,
}

/*
 * --------------------------------------------------------------------------
 * TTS
 * --------------------------------------------------------------------------
 *
 * We DO NOT use browser speechSynthesis anymore.
 *
 * Your Firefox/BlackArch environment has:
 *
 *   speechSynthesis.getVoices() -> []
 *
 * Therefore TTS is generated by Groq through:
 *
 *   /api/tts
 *
 * The browser only plays the returned WAV audio.
 * --------------------------------------------------------------------------
 */

let currentAudio: HTMLAudioElement | null = null
let currentAudioUrl: string | null = null

let speechGeneration = 0

/*
 * Keep this function because other components may use it.
 *
 * We now consider server-side audio TTS supported rather than
 * relying on Firefox speechSynthesis.
 */
export function isSpeechSynthesisSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    typeof window.Audio !== 'undefined'
  )
}

/*
 * --------------------------------------------------------------------------
 * Split text for Groq Orpheus
 * --------------------------------------------------------------------------
 *
 * Groq Orpheus has a 200-character input limit.
 *
 * We try to split on sentence boundaries first, then spaces.
 */
function splitText(
  text: string,
  maxLength = 200,
): string[] {
  const clean = text
    .replace(/\s+/g, ' ')
    .trim()

  if (!clean) {
    return []
  }

  if (clean.length <= maxLength) {
    return [clean]
  }

  const chunks: string[] = []

  let remaining = clean

  while (remaining.length > maxLength) {
    let cut = -1

    /*
     * Prefer sentence boundaries.
     */
    const sentenceEndings = [
      '. ',
      '? ',
      '! ',
      '। ',
    ]

    for (const ending of sentenceEndings) {
      const position =
        remaining.lastIndexOf(
          ending,
          maxLength,
        )

      if (position > cut) {
        cut =
          position +
          ending.trim().length
      }
    }

    /*
     * If there wasn't a useful sentence boundary,
     * split at the last space.
     */
    if (cut < 80) {
      cut = remaining.lastIndexOf(
        ' ',
        maxLength,
      )
    }

    /*
     * Extremely long word / no usable space.
     */
    if (cut < 1) {
      cut = maxLength
    }

    const chunk =
      remaining
        .slice(0, cut)
        .trim()

    if (chunk) {
      chunks.push(chunk)
    }

    remaining =
      remaining
        .slice(cut)
        .trim()
  }

  if (remaining) {
    chunks.push(remaining)
  }

  return chunks
}

/*
 * --------------------------------------------------------------------------
 * Stop current audio
 * --------------------------------------------------------------------------
 */
function cleanupAudio(): void {
  if (currentAudio) {
    try {
      currentAudio.pause()
      currentAudio.currentTime = 0
      currentAudio.src = ''
    } catch {
      // Ignore cleanup errors.
    }

    currentAudio.onplay = null
    currentAudio.onended = null
    currentAudio.onerror = null

    currentAudio = null
  }

  if (currentAudioUrl) {
    try {
      URL.revokeObjectURL(
        currentAudioUrl,
      )
    } catch {
      // Ignore cleanup errors.
    }

    currentAudioUrl = null
  }
}

export function stopSpeaking(): void {
  console.log(
    '[TTS] Stopping speech',
  )

  /*
   * Incrementing this invalidates any currently
   * running async playback loop.
   */
  speechGeneration++

  cleanupAudio()
}

/*
 * --------------------------------------------------------------------------
 * Request one audio chunk from our server
 * --------------------------------------------------------------------------
 */
async function fetchTTS(
  text: string,
): Promise<Blob> {
  console.log(
    '[TTS] Requesting audio:',
    text,
  )

  const response = await fetch(
    '/api/tts',
    {
      method: 'POST',
      headers: {
        'Content-Type':
          'application/json',
      },
      body: JSON.stringify({
        text,
      }),
    },
  )

  if (!response.ok) {
    let message =
      `TTS request failed (${response.status})`

    try {
      const data =
        await response.json()

      if (
        data &&
        typeof data.error ===
          'string'
      ) {
        message = data.error
      }
    } catch {
      // Response wasn't JSON.
    }

    throw new Error(message)
  }

  const blob =
    await response.blob()

  console.log(
    '[TTS] Audio received:',
    blob.size,
    'bytes',
    blob.type,
  )

  if (!blob.size) {
    throw new Error(
      'TTS returned empty audio',
    )
  }

  return blob
}

/*
 * --------------------------------------------------------------------------
 * Play one WAV blob
 * --------------------------------------------------------------------------
 */
function playBlob(
  blob: Blob,
  generation: number,
  handlers: {
    onStart?: () => void
    onEnd?: () => void
  },
): Promise<void> {
  return new Promise(
    (resolve, reject) => {
      /*
       * If a newer speech request started,
       * don't play this audio.
       */
      if (
        generation !== speechGeneration
      ) {
        resolve()
        return
      }

      const url =
        URL.createObjectURL(blob)

      currentAudioUrl = url

      const audio =
        new Audio(url)

      currentAudio = audio

      audio.preload = 'auto'
      audio.volume = 1

      let started = false
      let finished = false

      const cleanup = () => {
        if (finished) return

        finished = true

        audio.onplay = null
        audio.onended = null
        audio.onerror = null

        try {
          audio.pause()
          audio.currentTime = 0
          audio.src = ''
        } catch {
          // Ignore cleanup errors.
        }

        if (
          currentAudio === audio
        ) {
          currentAudio = null
        }

        if (
          currentAudioUrl === url
        ) {
          currentAudioUrl = null
        }

        try {
          URL.revokeObjectURL(
            url,
          )
        } catch {
          // Ignore cleanup errors.
        }
      }

      audio.onplay = () => {
        if (started) return

        started = true

        console.log(
          '[TTS] 🔊 AUDIO STARTED',
        )

        handlers.onStart?.()
      }

      audio.onended = () => {
        console.log(
          '[TTS] 🔊 AUDIO ENDED',
        )

        cleanup()
        resolve()
      }

      audio.onerror = () => {
        const error =
          audio.error

        console.error(
          '[TTS] ❌ AUDIO PLAYBACK ERROR:',
          error,
        )

        cleanup()

        reject(
          new Error(
            'Browser could not play the generated TTS audio.',
          ),
        )
      }

      void audio
        .play()
        .then(() => {
          console.log(
            '[TTS] audio.play() succeeded',
          )
        })
        .catch((error) => {
          console.error(
            '[TTS] ❌ audio.play() failed:',
            error,
          )

          cleanup()

          reject(error)
        })
    },
  )
}

/*
 * --------------------------------------------------------------------------
 * Public speak()
 * --------------------------------------------------------------------------
 *
 * IMPORTANT:
 *
 * The function remains synchronous from the caller's perspective.
 *
 * This means your existing:
 *
 *   say(replyText)
 *
 * does NOT need to change.
 */
export function speak(
  text: string,
  language: Language,
  handlers: {
    onStart?: () => void
    onEnd?: () => void
  } = {},
): void {
  console.log(
    '[TTS] speak() called:',
    text,
    'language:',
    language,
  )

  const cleanText =
    text.trim()

  if (!cleanText) {
    console.warn(
      '[TTS] Empty text',
    )

    handlers.onEnd?.()

    return
  }

  /*
   * Stop previous speech.
   */
  stopSpeaking()

  /*
   * This request gets its own generation number.
   */
  const generation =
    speechGeneration

  const chunks =
    splitText(cleanText)

  console.log(
    '[TTS] Text split into',
    chunks.length,
    'chunk(s)',
  )

  if (!chunks.length) {
    handlers.onEnd?.()
    return
  }

  void playChunks(
    chunks,
    generation,
    handlers,
  )
}

/*
 * --------------------------------------------------------------------------
 * Sequentially play all chunks
 * --------------------------------------------------------------------------
 */
async function playChunks(
  chunks: string[],
  generation: number,
  handlers: {
    onStart?: () => void
    onEnd?: () => void
  },
): Promise<void> {
  let started = false

  try {
    for (
      let index = 0;
      index < chunks.length;
      index++
    ) {
      /*
       * A newer speech request or stopSpeaking()
       * invalidated this playback.
       */
      if (
        generation !== speechGeneration
      ) {
        console.log(
          '[TTS] Playback cancelled',
        )

        return
      }

      const chunk =
        chunks[index]

      console.log(
        `[TTS] Chunk ${index + 1}/${chunks.length}:`,
        chunk,
      )

      const blob =
        await fetchTTS(chunk)

      /*
       * Check again because the network request
       * may have taken some time.
       */
      if (
        generation !== speechGeneration
      ) {
        console.log(
          '[TTS] Playback cancelled after fetch',
        )

        return
      }

      await playBlob(
        blob,
        generation,
        {
          onStart: () => {
            if (!started) {
              started = true

              handlers.onStart?.()
            }
          },
        },
      )
    }

    if (
      generation === speechGeneration
    ) {
      console.log(
        '[TTS] ✅ ALL AUDIO FINISHED',
      )

      handlers.onEnd?.()
    }
  } catch (error) {
    if (
      generation !== speechGeneration
    ) {
      return
    }

    console.error(
      '[TTS] ❌ TTS playback failed:',
      error,
    )

    handlers.onEnd?.()
  }
}

/*
 * --------------------------------------------------------------------------
 * STT
 * --------------------------------------------------------------------------
 */

export function isSpeechRecognitionSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    !!navigator.mediaDevices &&
    typeof navigator.mediaDevices
      .getUserMedia === 'function' &&
    typeof MediaRecorder !== 'undefined'
  )
}

export interface RecognitionHandle {
  stop: () => void
}

export async function listen(
  language: Language,
  handlers: {
    onResult: (
      transcript: string,
      isFinal: boolean,
    ) => void
    onEnd: () => void
    onError?: (err: string) => void
  },
): Promise<RecognitionHandle | null> {
  if (
    typeof window === 'undefined' ||
    !navigator.mediaDevices ||
    typeof navigator.mediaDevices
      .getUserMedia !==
      'function' ||
    typeof MediaRecorder === 'undefined'
  ) {
    handlers.onError?.(
      'Microphone recording is not supported by this browser.',
    )

    handlers.onEnd()

    return null
  }

  let stream: MediaStream | null =
    null

  let recorder: MediaRecorder | null =
    null

  let stopped = false

  try {
    stream =
      await navigator.mediaDevices.getUserMedia(
        {
          audio: true,
        },
      )

    if (stopped) {
      stream
        .getTracks()
        .forEach((track) =>
          track.stop(),
        )

      return null
    }

    const mimeTypes = [
      'audio/webm;codecs=opus',
      'audio/webm',
      'audio/ogg;codecs=opus',
      'audio/ogg',
    ]

    const mimeType =
      mimeTypes.find((type) =>
        MediaRecorder.isTypeSupported(
          type,
        ),
      ) || ''

    recorder = mimeType
      ? new MediaRecorder(
          stream,
          {
            mimeType,
          },
        )
      : new MediaRecorder(stream)

    const chunks: Blob[] = []

    recorder.ondataavailable = (
      event,
    ) => {
      if (event.data.size > 0) {
        chunks.push(
          event.data,
        )
      }
    }

    recorder.onerror = () => {
      handlers.onError?.(
        'Microphone recording failed.',
      )
    }

    recorder.onstop = async () => {
      try {
        if (!chunks.length) {
          throw new Error(
            'No audio was recorded.',
          )
        }

        const blob =
          new Blob(chunks, {
            type:
              recorder?.mimeType ||
              mimeType ||
              'audio/webm',
          })

        console.log(
          '[STT] Recorded audio:',
          blob.size,
          blob.type,
        )

        const formData =
          new FormData()

        const extension =
          blob.type.includes(
            'ogg',
          )
            ? 'ogg'
            : 'webm'

        formData.append(
          'audio',
          blob,
          `voice.${extension}`,
        )

        const whisperLanguage =
          whisperLangMap[
            language
          ]

        if (whisperLanguage) {
          formData.append(
            'language',
            whisperLanguage,
          )
        }

        console.log(
          '[STT] Sending audio to /api/stt...',
        )

        const response =
          await fetch(
            '/api/stt',
            {
              method: 'POST',
              body: formData,
            },
          )

        const data =
          await response.json()

        if (!response.ok) {
          throw new Error(
            data.error ||
              'Speech transcription failed.',
          )
        }

        const text =
          typeof data.text ===
          'string'
            ? data.text.trim()
            : ''

        if (!text) {
          throw new Error(
            'No speech detected.',
          )
        }

        console.log(
          '[STT] Transcription:',
          text,
        )

        handlers.onResult(
          text,
          true,
        )
      } catch (error) {
        console.error(
          '[STT] Error:',
          error,
        )

        handlers.onError?.(
          error instanceof Error
            ? error.message
            : 'Speech recognition failed.',
        )
      } finally {
        stream
          ?.getTracks()
          .forEach((track) =>
            track.stop(),
          )

        handlers.onEnd()
      }
    }

    recorder.start()

    console.log(
      '[STT] Recording started',
    )

    return {
      stop: () => {
        if (stopped) {
          return
        }

        stopped = true

        if (
          recorder &&
          recorder.state !==
            'inactive'
        ) {
          recorder.stop()
        }
      },
    }
  } catch (error) {
    stream
      ?.getTracks()
      .forEach((track) =>
        track.stop(),
      )

    console.error(
      '[STT] Microphone error:',
      error,
    )

    handlers.onError?.(
      error instanceof Error
        ? error.message
        : 'Could not access microphone.',
    )

    handlers.onEnd()

    return null
  }
}
